import{a as g,S as y,i}from"./assets/vendor-BDaiwwc1.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const d of r.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&n(d)}).observe(document,{childList:!0,subtree:!0});function e(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(t){if(t.ep)return;t.ep=!0;const r=e(t);fetch(t.href,r)}})();const L="47393143-e8759780233395bfabd4940e8",b="https://pixabay.com/api/",u=async(s,o)=>{const e=new URLSearchParams({key:L,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15}),{data:n}=await g.get(`${b}?${e}`);return n},v=new y(".list-item a");function f(s){const o=s.map(e=>`<li class="list-item">
      <a href="${e.largeImageURL}"><img src="${e.webformatURL}" alt="${e.tags}"></a>
      <div class="info">
      <p>Likes<span>${e.likes}</span></p>
    <p>Views<span>${e.views}</span></p>
    <p>Comments<span>${e.comments}</span></p>
    <p>Downloads<span>${e.downloads}</span></p>
    </div>
    </li>`).join("");h.insertAdjacentHTML("beforeend",o),v.refresh()}const m=document.querySelector(".form-search"),h=document.querySelector(".image-list"),c=document.querySelector(".loader"),l=document.querySelector(".button-to-load");let p="",a=1;m.addEventListener("submit",w);l.addEventListener("click",S);async function w(s){s.preventDefault();const{search:o}=s.currentTarget.elements;if(o.value.trim()==="")return i.error({position:"topRight",message:"Please fill in the field"});h.innerHTML="",a=1,l.classList.add("hidden"),c.classList.remove("hidden"),p=o.value.trim();try{const e=await u(p,a);if(e.hits.length===0)return i.info({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"});f(e.hits),m.reset(),e.hits.length===15&&l.classList.remove("hidden")}catch(e){i.error({position:"topRight",message:e.message})}finally{c.classList.add("hidden")}}async function S(){a+=1,c.classList.remove("hidden");try{const s=await u(p,a);f(s.hits),Math.ceil(s.totalHits/15)===a&&(l.classList.add("hidden"),i.info({position:"topRight",title:"End of results",message:"We're sorry, but you've reached the end of search results."}))}catch(s){i.error({position:"topRight",message:s.message})}finally{c.classList.add("hidden")}}
//# sourceMappingURL=index.js.map
