import{a as g,S as y,i}from"./assets/vendor-BDaiwwc1.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const d of o.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&c(d)}).observe(document,{childList:!0,subtree:!0});function e(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function c(t){if(t.ep)return;t.ep=!0;const o=e(t);fetch(t.href,o)}})();const L="47393143-e8759780233395bfabd4940e8",b="https://pixabay.com/api/",u=async(s,r)=>{const e=new URLSearchParams({key:L,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15}),{data:c}=await g.get(`${b}?${e}`);return c},v=new y(".list-item a");function h(s){const r=s.map(e=>`<li class="list-item">
      <a href="${e.largeImageURL}"><img src="${e.webformatURL}" alt="${e.tags}"></a>
      <div class="info">
      <p>Likes<span>${e.likes}</span></p>
    <p>Views<span>${e.views}</span></p>
    <p>Comments<span>${e.comments}</span></p>
    <p>Downloads<span>${e.downloads}</span></p>
    </div>
    </li>`).join("");m.insertAdjacentHTML("beforeend",r),v.refresh()}const f=document.querySelector(".form-search"),m=document.querySelector(".image-list"),l=document.querySelector(".loader"),n=document.querySelector(".button-to-load");let p="",a=1;f.addEventListener("submit",w);n.addEventListener("click",R);async function w(s){s.preventDefault();const{search:r}=s.currentTarget.elements;if(r.value.trim()==="")return i.error({position:"topRight",message:"Please fill in the field"});m.innerHTML="",a=1,n.classList.add("hidden"),p=r.value.trim(),l.classList.remove("hidden");try{const e=await u(p,a);if(e.hits.length===0)return i.info({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"});h(e.hits),f.reset(),e.hits.length===15&&n.classList.remove("hidden")}catch(e){i.error({position:"topRight",message:e.message})}finally{l.classList.add("hidden")}}async function R(){a+=1,l.classList.remove("hidden"),n.classList.add("hidden");try{const s=await u(p,a);h(s.hits),Math.ceil(s.totalHits/15)===a&&(n.classList.add("hidden"),i.info({position:"topRight",title:"End of results",message:"We're sorry, but you've reached the end of search results."}));const{height:r}=image.firstElementChild.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}catch(s){i.error({position:"topRight",message:s.message})}finally{l.classList.add("hidden")}}
//# sourceMappingURL=index.js.map
